filter:
    paths:
       - app/*
       - resources/*
build:
    environment:
        php: 8.0
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
