name: Code style PHP

on:
  push:
    branches-ignore:
      - '**-dev'
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    name: phpcs PHP/PHTML

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: composer validate

      - run: composer global require squizlabs/php_codesniffer=* --quiet

      - name: PHPCS
        run: ~/.composer/vendor/bin/phpcs -s
